name: latha_tuition_app
description: "Latha's tuition app"

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.2.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    liquid_swipe: ^3.1.0
    smooth_page_indicator: ^1.1.0
    flutter_svg: ^2.0.9
    flutter_riverpod: ^2.4.10
    curved_navigation_bar: ^1.0.3
    table_calendar: ^3.1.0
    intl: ^0.19.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
    uses-material-design: true

    assets:
        - assets/images/

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins/Poppins-Thin.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-Light.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-Regular.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-Medium.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-Bold.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
                weight: 100
              - asset: assets/fonts/Poppins/Poppins-Black.ttf
                weight: 100
